"""
MCP Deterministic Generator

Template-based MCP server code generation without LLM.
Useful for simple APIs or when LLM is unavailable.

This provides a fallback generation method that doesn't require API keys
or network connectivity. It generates syntactically correct MCP servers
from tool definitions using templates.
"""

from typing import List, Dict, Any, Optional
import json
import re


def generate_mcp_server_code(
    tools: List[Dict[str, Any]],
    server_name: str = "generated_mcp_server",
    description: str = "Auto-generated MCP server",
    base_url: Optional[str] = None
) -> str:
    """
    Generate MCP server code from tool definitions.
    
    Args:
        tools: List of tool definitions with name, description, parameters, etc.
        server_name: Name of the MCP server
        description: Server description
        base_url: Optional base URL for API calls
        
    Returns:
        Complete Python code for MCP server
        
    Example tool definition:
        {
            "name": "get_user",
            "description": "Get user information by ID",
            "parameters": [
                {"name": "user_id", "type": "str", "description": "User ID"}
            ],
            "method": "GET",
            "endpoint": "/users/{user_id}",
            "returns": "Dict[str, Any]"
        }
    """
    # Validate inputs
    if not tools:
        raise ValueError("At least one tool definition is required")
    
    if not server_name or not server_name.replace("_", "").isalnum():
        raise ValueError("Server name must be alphanumeric with underscores")
    
    # Generate imports
    imports = _generate_imports(tools, base_url)
    
    # Generate server instance
    server_instance = _generate_server_instance(server_name, description)
    
    # Generate tool functions
    tool_functions = []
    for tool in tools:
        try:
            func_code = _generate_tool_function(tool, base_url)
            tool_functions.append(func_code)
        except Exception as e:
            # Skip invalid tool definitions but log the error
            print(f"Warning: Skipping tool '{tool.get('name', 'unknown')}': {e}")
            continue
    
    if not tool_functions:
        raise ValueError("No valid tool functions could be generated")
    
    # Generate main block
    main_block = _generate_main_block()
    
    # Assemble complete code
    code = f'''{imports}

{server_instance}

{chr(10).join(tool_functions)}

{main_block}
'''
    
    return code


def _generate_imports(tools: List[Dict[str, Any]], base_url: Optional[str]) -> str:
    """Generate import statements based on tool requirements."""
    imports = [
        '"""',
        'Auto-generated MCP server using FastMCP.',
        'Generated by MCPValidator3 deterministic generator.',
        '"""',
        '',
        'from fastmcp import FastMCP',
        'from typing import Any, Dict, List, Optional',
    ]
    
    # Check if any tool needs HTTP client
    needs_http = any(
        tool.get("method") or tool.get("endpoint") or base_url
        for tool in tools
    )
    
    if needs_http:
        imports.append('import httpx')
    
    # Check if any tool needs JSON
    needs_json = any(
        tool.get("returns") == "Dict[str, Any]" or
        tool.get("returns") == "List[Dict[str, Any]]"
        for tool in tools
    )
    
    if needs_json:
        imports.append('import json')
    
    return '\n'.join(imports)


def _generate_server_instance(server_name: str, description: str) -> str:
    """Generate FastMCP server instance."""
    return f'''# Initialize MCP server
mcp = FastMCP("{server_name}")

# Server configuration
BASE_URL = "https://api.example.com"  # Update with actual API base URL
TIMEOUT = 30.0  # HTTP timeout in seconds'''


def _generate_tool_function(tool: Dict[str, Any], base_url: Optional[str]) -> str:
    """Generate a single tool function from definition."""
    # Extract tool metadata
    name = tool.get("name")
    if not name:
        raise ValueError("Tool must have a 'name' field")
    
    # Validate and sanitize name
    name = _sanitize_function_name(name)
    
    description = tool.get("description", "No description provided")
    parameters = tool.get("parameters", [])
    method = tool.get("method", "GET").upper()
    endpoint = tool.get("endpoint", "")
    returns = tool.get("returns", "Dict[str, Any]")
    
    # Generate parameter list with type hints
    params = []
    param_docs = []
    for param in parameters:
        param_name = param.get("name", "param")
        param_type = param.get("type", "str")
        param_desc = param.get("description", "")
        param_required = param.get("required", True)
        
        # Sanitize parameter name
        param_name = _sanitize_parameter_name(param_name)
        
        # Add Optional wrapper if not required
        if not param_required:
            param_type = f"Optional[{param_type}]"
            params.append(f"{param_name}: {param_type} = None")
        else:
            params.append(f"{param_name}: {param_type}")
        
        # Add to docstring
        if param_desc:
            param_docs.append(f"        {param_name}: {param_desc}")
    
    param_str = ", ".join(params) if params else ""
    param_doc_str = "\n".join(param_docs) if param_docs else "        No parameters"
    
    # Generate function body
    if endpoint and method:
        body = _generate_http_call_body(name, method, endpoint, parameters, base_url)
    else:
        body = _generate_placeholder_body(name)
    
    # Generate complete function
    func = f'''@mcp.tool
async def {name}({param_str}) -> {returns}:
    """
    {description}
    
    Args:
{param_doc_str}
    
    Returns:
        {returns}: Response from the API
    """
{body}'''
    
    return func


def _generate_http_call_body(
    name: str,
    method: str,
    endpoint: str,
    parameters: List[Dict[str, Any]],
    base_url: Optional[str]
) -> str:
    """Generate HTTP call implementation."""
    # Build URL with path parameters
    url_parts = []
    url_parts.append('    url = f"{BASE_URL}' + endpoint + '"')
    
    # Check if endpoint has path parameters (e.g., /users/{user_id})
    path_params = re.findall(r'\{(\w+)\}', endpoint)
    
    # Build request body for POST/PUT/PATCH
    if method in ["POST", "PUT", "PATCH"]:
        body_params = [p for p in parameters if p.get("name") not in path_params]
        if body_params:
            body_dict = ", ".join([f'"{p.get("name")}": {_sanitize_parameter_name(p.get("name"))}' for p in body_params])
            url_parts.append(f'    data = {{{body_dict}}}')
    
    # Build query parameters for GET/DELETE
    elif method in ["GET", "DELETE"]:
        query_params = [p for p in parameters if p.get("name") not in path_params]
        if query_params:
            params_dict = ", ".join([f'"{p.get("name")}": {_sanitize_parameter_name(p.get("name"))}' for p in query_params])
            url_parts.append(f'    params = {{{params_dict}}}')
    
    # Generate HTTP call
    body_lines = url_parts + [
        '    ',
        '    try:',
        '        async with httpx.AsyncClient(timeout=TIMEOUT) as client:',
    ]
    
    # Add appropriate HTTP method call
    if method == "GET":
        if any(p.get("name") not in path_params for p in parameters):
            body_lines.append('            response = await client.get(url, params=params)')
        else:
            body_lines.append('            response = await client.get(url)')
    elif method == "POST":
        body_lines.append('            response = await client.post(url, json=data)')
    elif method == "PUT":
        body_lines.append('            response = await client.put(url, json=data)')
    elif method == "PATCH":
        body_lines.append('            response = await client.patch(url, json=data)')
    elif method == "DELETE":
        if any(p.get("name") not in path_params for p in parameters):
            body_lines.append('            response = await client.delete(url, params=params)')
        else:
            body_lines.append('            response = await client.delete(url)')
    
    body_lines.extend([
        '            response.raise_for_status()',
        '            return response.json()',
        '    except httpx.HTTPError as e:',
        '        return {"error": f"HTTP error occurred: {str(e)}"}',
        '    except Exception as e:',
        '        return {"error": f"An error occurred: {str(e)}"}',
    ])
    
    return '\n'.join(body_lines)


def _generate_placeholder_body(name: str) -> str:
    """Generate placeholder implementation for tools without endpoint info."""
    return '''    # TODO: Implement tool logic
    # This is a placeholder implementation
    return {
        "status": "success",
        "message": f"Tool '{name}' executed successfully",
        "note": "This is a placeholder. Implement actual logic here."
    }'''.replace("'{name}'", f"'{name}'")


def _generate_main_block() -> str:
    """Generate main execution block."""
    return '''if __name__ == "__main__":
    # Run the MCP server
    mcp.run()'''


def _sanitize_function_name(name: str) -> str:
    """
    Sanitize function name to be valid Python identifier.
    
    - Convert to lowercase
    - Replace spaces and hyphens with underscores
    - Remove invalid characters
    - Ensure doesn't start with number
    """
    # Convert to lowercase
    name = name.lower()
    
    # Replace spaces and hyphens with underscores
    name = re.sub(r'[\s\-]+', '_', name)
    
    # Remove invalid characters (keep only alphanumeric and underscore)
    name = re.sub(r'[^\w]', '', name)
    
    # Ensure doesn't start with number
    if name and name[0].isdigit():
        name = f"tool_{name}"
    
    # Ensure not empty
    if not name:
        name = "unnamed_tool"
    
    return name


def _sanitize_parameter_name(name: str) -> str:
    """Sanitize parameter name to be valid Python identifier."""
    return _sanitize_function_name(name)


def generate_from_openapi(openapi_spec: Dict[str, Any]) -> str:
    """
    Generate MCP server from OpenAPI/Swagger specification.
    
    Args:
        openapi_spec: OpenAPI specification dictionary
        
    Returns:
        Generated MCP server code
    """
    tools = []
    
    # Extract server info
    info = openapi_spec.get("info", {})
    server_name = info.get("title", "api_server").lower().replace(" ", "_")
    description = info.get("description", "API server")
    
    # Extract base URL
    servers = openapi_spec.get("servers", [])
    base_url = servers[0].get("url") if servers else None
    
    # Extract paths and operations
    paths = openapi_spec.get("paths", {})
    for path, path_item in paths.items():
        for method, operation in path_item.items():
            if method.upper() not in ["GET", "POST", "PUT", "PATCH", "DELETE"]:
                continue
            
            # Extract operation details
            operation_id = operation.get("operationId", f"{method}_{path.replace('/', '_')}")
            summary = operation.get("summary", "")
            parameters = []
            
            # Extract parameters
            for param in operation.get("parameters", []):
                parameters.append({
                    "name": param.get("name"),
                    "type": _openapi_type_to_python(param.get("schema", {}).get("type", "string")),
                    "description": param.get("description", ""),
                    "required": param.get("required", False)
                })
            
            # Create tool definition
            tools.append({
                "name": _sanitize_function_name(operation_id),
                "description": summary or f"{method.upper()} {path}",
                "parameters": parameters,
                "method": method.upper(),
                "endpoint": path,
                "returns": "Dict[str, Any]"
            })
    
    return generate_mcp_server_code(tools, server_name, description, base_url)


def _openapi_type_to_python(openapi_type: str) -> str:
    """Convert OpenAPI type to Python type hint."""
    type_mapping = {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "array": "List[Any]",
        "object": "Dict[str, Any]"
    }
    return type_mapping.get(openapi_type, "str")


# Example usage
if __name__ == "__main__":
    # Example tool definitions
    example_tools = [
        {
            "name": "get_user",
            "description": "Get user information by ID",
            "parameters": [
                {"name": "user_id", "type": "str", "description": "User ID", "required": True}
            ],
            "method": "GET",
            "endpoint": "/users/{user_id}",
            "returns": "Dict[str, Any]"
        },
        {
            "name": "create_user",
            "description": "Create a new user",
            "parameters": [
                {"name": "name", "type": "str", "description": "User name", "required": True},
                {"name": "email", "type": "str", "description": "User email", "required": True},
                {"name": "age", "type": "int", "description": "User age", "required": False}
            ],
            "method": "POST",
            "endpoint": "/users",
            "returns": "Dict[str, Any]"
        }
    ]
    
    # Generate code
    code = generate_mcp_server_code(
        tools=example_tools,
        server_name="user_api_server",
        description="User management API server"
    )
    
    print(code)
