"""
Deterministic MCP server generator from a live MongoDB database.

Flow:
  1. Connect to MongoDB using the provided URI + dbname
  2. Discover schema (collections → fields + types)
  3. Generate a FastMCP Python server with one tool per collection
  4. Return the generated code string
"""
from __future__ import annotations
import json
import re
from datetime import datetime, timezone


def _safe_name(name: str) -> str:
    """Convert a collection name to a valid Python identifier."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", name).strip("_") or "collection"


def connect_and_get_schema(uri: str, dbname: str) -> dict[str, list[dict]]:
    """
    Connect to MongoDB and return schema:
    { collection_name: [ {name, type}, ... ] }
    """
    from pymongo import MongoClient
    client = MongoClient(uri, serverSelectionTimeoutMS=5000)
    client.admin.command("ping")   # raises if not reachable
    db = client[dbname]

    schema: dict[str, list[dict]] = {}
    for col in db.list_collection_names():
        doc = db[col].find_one()
        if doc:
            schema[col] = [
                {"name": k, "type": type(v).__name__}
                for k, v in doc.items()
            ]
        else:
            schema[col] = []
    client.close()
    return schema


def generate_mcp_code(uri: str, dbname: str, schema: dict[str, list[dict]]) -> str:
    """
    Generate a complete FastMCP Python server from the discovered schema.
    Each collection gets:
      - query_{col}(filter_json, limit)   → list of documents
      - count_{col}(filter_json)          → int
    Plus shared tools: list_collections, get_schema, run_query
    """
    collections = list(schema.keys())
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []

    # ── Header ──────────────────────────────────────────────────────
    lines += [
        '"""',
        f'Auto-generated MCP server for MongoDB database: {dbname}',
        f'URI: {uri}',
        f'Collections: {", ".join(collections)}',
        f'Generated by AutoMCP on {ts}',
        '"""',
        "from __future__ import annotations",
        "import json",
        "from fastmcp import FastMCP",
        "from pymongo import MongoClient",
        "from bson import ObjectId",
        "",
        f'mcp = FastMCP("MongoDB:{dbname}")',
        "",
        "# ── Connection ──────────────────────────────────────────────",
        "_client = None",
        "",
        "def _get_db():",
        "    global _client",
        "    if _client is None:",
        f'        _client = MongoClient({repr(uri)}, serverSelectionTimeoutMS=5000)',
        f'    return _client[{repr(dbname)}]',
        "",
        "def _serialize(docs: list) -> list:",
        "    out = []",
        "    for d in docs:",
        "        row = {}",
        "        for k, v in d.items():",
        "            row[k] = str(v) if isinstance(v, ObjectId) else v",
        "        out.append(row)",
        "    return out",
        "",
    ]

    # ── Shared tools ─────────────────────────────────────────────────
    lines += [
        "# ── Shared tools ────────────────────────────────────────────",
        "@mcp.tool()",
        "def list_collections() -> list:",
        f'    """List all collections in the {dbname} database."""',
        "    return _get_db().list_collection_names()",
        "",
        "@mcp.tool()",
        "def get_schema() -> dict:",
        f'    """Return field names and types for every collection in {dbname}."""',
        "    result = {}",
        "    db = _get_db()",
        "    for col in db.list_collection_names():",
        "        doc = db[col].find_one()",
        "        if doc:",
        "            result[col] = {k: type(v).__name__ for k, v in doc.items()}",
        "        else:",
        "            result[col] = {}",
        "    return result",
        "",
        "@mcp.tool()",
        "def run_query(collection: str, filter_json: str = '{}', limit: int = 10) -> list:",
        '    """Run a find() query on any collection. filter_json must be valid JSON."""',
        "    try:",
        "        f = json.loads(filter_json) if filter_json.strip() not in ('{}', '') else {}",
        "        docs = list(_get_db()[collection].find(f).limit(limit))",
        "        return _serialize(docs)",
        "    except Exception as e:",
        "        return [{'error': str(e)}]",
        "",
    ]

    # ── Per-collection tools ─────────────────────────────────────────
    lines.append("# ── Per-collection tools ────────────────────────────────────")
    for col in collections:
        fn = _safe_name(col)
        fields = [f["name"] for f in schema[col] if f["name"] != "_id"]
        field_info = ", ".join(fields[:8]) or "no fields detected"

        lines += [
            f"@mcp.tool()",
            f"def query_{fn}(filter_json: str = '{{}}', limit: int = 10) -> list:",
            f'    """Query the {col} collection (fields: {field_info}). filter_json: MongoDB filter as JSON."""',
            f"    try:",
            f"        f = json.loads(filter_json) if filter_json.strip() not in ('{{}}', '') else {{}}",
            f"        docs = list(_get_db()[{repr(col)}].find(f).limit(limit))",
            f"        return _serialize(docs)",
            f"    except Exception as e:",
            f"        return [{{'error': str(e)}}]",
            "",
            f"@mcp.tool()",
            f"def count_{fn}(filter_json: str = '{{}}') -> int:",
            f'    """Count documents in the {col} collection matching filter_json."""',
            f"    try:",
            f"        f = json.loads(filter_json) if filter_json.strip() not in ('{{}}', '') else {{}}",
            f"        return _get_db()[{repr(col)}].count_documents(f)",
            f"    except Exception as e:",
            f"        return -1",
            "",
        ]

    # ── Entry point ──────────────────────────────────────────────────
    lines += [
        'if __name__ == "__main__":',
        "    mcp.run()",
    ]

    return "\n".join(lines)
